apiVersion: v1
kind: ServiceAccount
metadata:
  name: installplan-approver
  namespace: operator-upgrade-approver
  labels:
    app.kubernetes.io/name: installplan-approver
    app.kubernetes.io/part-of: operator-upgrade-approver
